### ISSUE TITLE
Publish DEPRECATED note to npm

### ISSUE THREAD

**Issue by gerhardsletten** [jonschlinkert/object-pick#1]
You should publish a new version on npm so user that only visit that site will see that this module is DEPRECATED

**Comment by jonschlinkert** [comment]
Did you even look before you commented?

```
object-pick@0.1.2: Deprecated as of version 0.1.2 please use object.pick instead.
```

**Comment by gerhardsletten** [comment]
Yes, I did see it here on github, but you will have to publish a new version to npm to update the readme there: [npmjs.com/package/object-pick](https://www.npmjs.com/package/object-pick)

![image](https://cloud.githubusercontent.com/assets/63344/18645825/119fc960-7eaf-11e6-867b-7652f8281eb4.png)
